"""add_biometric_logs_table

Revision ID: 9d826f3017ec
Revises: f289d0a71b4c
Create Date: 2026-09-29 22:03:00.974377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d826f3017ec'
down_revision: Union[str, Sequence[str], None] = 'f289d0a71b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometric_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('arms_cm', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_logs_id'), 'biometric_logs', ['id'], unique=False)
    op.create_index(op.f('ix_biometric_logs_logged_at'), 'biometric_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_biometric_logs_user_id'), 'biometric_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biometric_logs_user_id'), table_name='biometric_logs')
    op.drop_index(op.f('ix_biometric_logs_logged_at'), table_name='biometric_logs')
    op.drop_index(op.f('ix_biometric_logs_id'), table_name='biometric_logs')
    op.drop_table('biometric_logs')
    # ### end Alembic commands ###
