"""add_grocery_and_diet_models

Revision ID: ba07595ca352
Revises: 6d2b7f766336
Create Date: 2026-09-29 20:13:21.154471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba07595ca352'
down_revision: Union[str, Sequence[str], None] = '6d2b7f766336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fats_g', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantry_items_id'), 'pantry_items', ['id'], unique=False)
    op.create_index(op.f('ix_pantry_items_name'), 'pantry_items', ['name'], unique=False)
    op.create_index(op.f('ix_pantry_items_user_id'), 'pantry_items', ['user_id'], unique=False)
    op.create_table('saved_meal_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('total_protein_g', sa.Float(), nullable=False),
    sa.Column('total_carbs_g', sa.Float(), nullable=False),
    sa.Column('total_fats_g', sa.Float(), nullable=False),
    sa.Column('meals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_meal_plans_id'), 'saved_meal_plans', ['id'], unique=False)
    op.create_index(op.f('ix_saved_meal_plans_user_id'), 'saved_meal_plans', ['user_id'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_items_id'), 'shopping_list_items', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_user_id'), 'shopping_list_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_list_items_user_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_id'), table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index(op.f('ix_saved_meal_plans_user_id'), table_name='saved_meal_plans')
    op.drop_index(op.f('ix_saved_meal_plans_id'), table_name='saved_meal_plans')
    op.drop_table('saved_meal_plans')
    op.drop_index(op.f('ix_pantry_items_user_id'), table_name='pantry_items')
    op.drop_index(op.f('ix_pantry_items_name'), table_name='pantry_items')
    op.drop_index(op.f('ix_pantry_items_id'), table_name='pantry_items')
    op.drop_table('pantry_items')
    # ### end Alembic commands ###
